~essencias = ();

~essencias[\citronela] = ["citronellal","geraniol","limonene","geranyl_acetate"];
~essencias[\cardamomo] = ["alpha_terpineol","myrcene","limonene","beta_phellandrene","eucalyptol","sabinene","heptane"];
~essencias[\louro] = ["eucalyptol","phellandrene","linalool","alpha_terpineol","lauric_acid","myrcene","eugenol"];
~essencias[\tomilho] = ["thymol","p_cymene","myrcene","borneol","linalool"];
~essencias[\litsea_cubeba] = ["citral","limonene","methyl_heptenone","camphene"];
~essencias[\manjericao] = ["methyl_chavicol","linalool","eucalyptol","eugenol","myrcene"];